AllCops:
  TargetRubyVersion: 2.3

# Uniform block layout
Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

# Be relatively lenient with line length
Metrics/LineLength:
  Max: 92

# Prefer no parentheses in method definitions
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

inherit_from: .rubocop_todo.yml
