# Uniform block layout
Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

# Be relatively lenient with line length
Metrics/LineLength:
  Max: 92

# Using eval is the bread and butter of Iba
Security/Eval:
  Enabled: false

# Prefer no parentheses in method definitions
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

inherit_from: .rubocop_todo.yml
