language: ruby

dist: xenial

cache:
  bundler: true

jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: jruby-9.2
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang
    - rvm: 2.7.1
      name: "RuboCop"
      before_install: []
      script: bundle exec rubocop
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang

branches:
  only:
    - master
