dist: xenial
language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - jruby-9.2.8.0
  - jruby-head
  - rubinius-4.6
  - ruby-head
  - ruby-head-clang

matrix:
  allow_failures:
    - rvm: jruby-9.2.8.0
    - rvm: jruby-head
    - rvm: rubinius-4.6
    - rvm: ruby-head
    - rvm: ruby-head-clang

branches:
  only:
    - master
