language: ruby
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - jruby-9.1.6.0
  - jruby-head
  - rubinius-3.69
  - ruby-head
  - ruby-head-clang
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: jruby-9.1.6.0
    - rvm: jruby-head
    - rvm: rubinius-3.69
    - rvm: ruby-head
    - rvm: ruby-head-clang
